name: Upload Package to Helix

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Package.toml
      - Client/**
      - Server/**
      - Shared/**

jobs:
  upload-package:
    runs-on: ubuntu-latest

    steps:
      - name: Use deploy package action
        uses: hypersonic-laboratories/deploy-package@main
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
          package_name: 'helix-weapons'
